version: "3.7"

services:
  server:
    image: lv2
    ports:
      - "3007:3007"
      - "8080:8080"
    links:
      - mongodb
    env_file:
      - ./.env
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - TMN_CODE=5XK2JZPT
      - HASH_SECRET=CIXCUTQDKONMNLVCNGPAASFGGMSHNNUU
      - VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - RETURN_URL=http://enterprise.bkservice.tk/payment-result
      - FLASK_ENV=development
      - FLASK_APP=bkservice.py
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    env_file:
      - ./.env
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nestjs-test
    logging:
      driver: none



volumes:
  db:
