#version: "3.3"
#
#services:
#  server:
#    image: lv2
#    ports:
#      - "3007:3007"
#      - "8080:8080"
#    links:
#      - mongodb
#    env_file:
#      - ./.env
#    depends_on:
#      - mongodb
#    environment:
#      - DB_HOST=mongodb
#      - DB_USER=$DB_USER
#      - DB_PASSWORD=$DB_PASSWORD
#      - DB_NAME=$DB_NAME
#      - DB_PORT=$DB_PORT
#      - TMN_CODE=5XK2JZPT
#      - HASH_SECRET=CIXCUTQDKONMNLVCNGPAASFGGMSHNNUU
#      - VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#      - RETURN_URL=http://enterprise.bkservice.tk/payment-result
#      - FLASK_ENV=development
#      - FLASK_APP=bkservice.py
#    stdin_open: true
#    tty: true
#  mongodb:
#    image: mongo
#    env_file:
#      - ./.env
#    ports:
#      - "27018:27017"
#    restart: always
#    volumes:
#      - db:/data/db
#    environment:
#      - MONGO_INITDB_DATABASE=nestjs-test
#    logging:
#      driver: none
#volumes:
#  db:
version: "3.3"

services:
  server:
    image: lv2
    ports:
      - "3007:3007"
      - "8080:8080"
    links:
      - mongodb
    env_file:
      - ./.env
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - TMN_CODE=5XK2JZPT
      - HASH_SECRET=CIXCUTQDKONMNLVCNGPAASFGGMSHNNUU
      - VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - RETURN_URL=http://enterprise.bkservice.tk/payment-result
      - FLASK_ENV=development
      - FLASK_APP=bkservice.py
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    env_file:
      - ./.env
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nestjs-test
    logging:
      driver: none
  ai:
    image: lvai2
    build:
      context: ./AI
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=bkservice.py
    stdin_open: true
    tty: true
  client-customer:
    image: lv-client-customer
    ports:
      - "80:5000"
    build:
      context: ../client_customer/BK-Service
    env_file:
      - ./.env
    environment:
      - REACT_APP_SOCKET_URI= http://3.26.113.160:8080
      - REACT_APP_SOCKET_URI_DEV= http://localhost:8080
      - REACT_APP_API_URL_DEV = http://localhost:3007
      - REACT_APP_API_URL = http://3.26.113.160:3007
    stdin_open: true
    tty: true
  client-enterprise:
    image: lv-client
    ports:
      - "81:5000"
    build:
      context: ../client_enterprise/BK-Service
    env_file:
      - ./.env
    environment:
      - REACT_APP_SOCKET_URI= http://3.26.113.160:8080
      - REACT_APP_SOCKET_URI_DEV= http://localhost:8080
      - REACT_APP_API_URL_DEV = http://localhost:3007
      - REACT_APP_API_URL = http://3.26.113.160:3007
    stdin_open: true
    tty: true
volumes:
  db: